# Header
menu:
  主页: /
  随笔集: /categories/随笔集
  大数据: /categories/大数据技术
  Android: /categories/Android技术
  前端: /categories/前端技术
  后端: /categories/后端技术
  数据库: /categories/数据库
  进阶: /categories/进阶
  其他: /categories/其他

# SubNav
subnav:
  github: "https://github.com/CentMeng"
  weibo: "http://weibo.com/u/5088952753?refer_flag=1001030101_&is_all=1"
  rss: "http://blog.csdn.net/u011930471"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: 

# Content
excerpt_link: more
fancybox: true
mathjax: false

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: /img/avatar.jpg

#是否开启分享
share_jia: true
share_addthis: false

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: centmeng

# 如不需要，将该项置为false
# 比如
#smart_menu:
#  friends: false

smart_menu:
  innerArchive: '所有文章'
  tagcloud: '标签'
  friends: '友链'
  aboutme: false

friends:
  招商中: http://localhost:4000/
 

aboutme: 很惭愧<br><br>只做了一点微小的工作<br>谢谢大家

# 打赏
# 请在需要打赏的文章的md文件头部，设置属性reward: true

# 打赏基础设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: '谢谢您请我吃糖果'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: http://obbbnmuwc.bkt.clouddn.com/zhifubao.png
# 微信二维码图片地址
weixin: http://obbbnmuwc.bkt.clouddn.com/weixin.png